### ISSUE TITLE
Trouble getting started...

### ISSUE THREAD

**Issue by RobSeder** [MicrosoftLearning/Django#1]
If I try to sync the DB - the first error I get is:

    Traceback (most recent call last):
    File "C:\Users\RobSe\Downloads\Django-master\Demos\MusicStore\manage.py", line 15, in <module>
    from django.core.management import execute_from_command_line
    ImportError: No module named 'django'

So, if I right-click on the "env" Python Environment within the project and choose Install from requirements.txt it fails with this in the output window:

    Installing 'pip' package manager.
    Downloading setuptools from https://go.microsoft.com/fwlink/?LinkId=317603
    Installing from setuptools-15.1
    running install
    error: can't create or remove files in install directory
    The following error occurred while trying to add or remove files in the installation directory:
    [Errno 2] No such file or directory: 'C:\\Data\\Django-master\\Demos\\MusicStore\\env\\Lib\\site-packages\\test-easy-install-9560.write-test'
    The installation directory you specified (via --install-dir, --prefix, or the distutils default setting) was:
    C:\Data\Django-master\Demos\MusicStore\env\Lib\site-packages\
    This directory does not currently exist.  Please create it and try again, or choose a different installation directory (using the -d or --install-dir option).
    Traceback (most recent call last):
     File "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.2\pip_downloader.py", line 64, in <module>
     subprocess.check_call([sys.executable, 'setup.py', 'install'])
    File "C:\Python34\lib\subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Data\\Django-master\\Demos\\MusicStore\\env\\Scripts\\python.exe', 'setup.py', 'install']' returned non-zero exit status 1
    'pip' failed to install. Exit code: 1
    C:\Data\Django-master\Demos\MusicStore\env\Scripts\python.exe: No module named pip````

Now, I am running Visual Studio as administrator and the directory has Everyone:FullControl. It would seem it has all the permission it needs.

This is running on VIsual Studio 2015 RC (with the latest RC version of PTVS) on WIndows 10 (build 10130). Any ideas?

**Comment by GeekTrainer** [comment]
I had bad luck with the newest RC, and specifically around those types of errors. I'd suggest using VS 2013 and version 2.1 of PTVS.

Also, as we mentioned in the video, you won't want to use Sync DB; that is a deprecated command.

**Comment by RobSeder** [comment]
@GeekTrainer Thanks - I did note in the MVA talk you said that, but the [ReadMe.mht](https://github.com/MicrosoftLearning/Django/blob/master/Demos/MusicStore/readme.mht) specifically/explicitly says to do a sync first.

So let me ask a different way: if I pull down the source and open it in VS, should I do anything first? Or - just hit F5 to start?

I realize I could just wait a week until the session video is published, but I found it VERY compelling and would like to dig in early! Thanks

**Comment by GeekTrainer** [comment]
The screen is a bit outdated.

After pulling it down, you'll need to create the environment from the requirements.txt file, and then create the database by using the python manage.py migrate command

**Comment by RobSeder** [comment]
Great - thank you!!

**Comment by RobSeder** [comment]
@GeekTrainer Do you know when the sessions from Microsoft Virtual Academy are going to be published? It's been 2+ weeks and they are still not up: http://www.microsoftvirtualacademy.com/Studies/SearchResult.aspx?q=django

Thanks!

**Comment by GeekTrainer** [comment]
Things got delayed because of the US holiday. This should be up soon. I apologize for the delay.

**Comment by RobSeder** [comment]
@GeekTrainer Any update on when this session will be uploaded? The live event was hosted 4 weeks ago, today!

**Comment by GeekTrainer** [comment]
Soon. I unfortunately don't have a date, but we are working on getting it posted.
